# Site settings
title: "Jessica Graves"
description: "Jessica Graves - biostatistician"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jess L. Graves"
resume_title:                   "Biostatistician/Data Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jessica.lynn.graves@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "jessica.lynn.graves@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am senior biostatistician excited by building and executing quality research clinical trials and programs that leverage statistical techniques to produce interpretable and clinically impactful results.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    true
resume_section_papers:          true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/JessLGraves"
  resume_scholar_url:        "https://scholar.google.com/citations?user=7Rmo0iUAAAAJ&hl=en&oi=ao"
#   resume_twitter_url:           ""
#   resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jessicalgraves/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://jessgraves.shinyapps.io/power_app/"
#   resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
